global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cass'
    static_configs:
      - targets:
          - cass1:9080
          - cass2:9080
          - cass3:9080
          - cass4:9080
          - cass5:9080
